# Generated by Django 4.1.1 on 2022-09-08 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOutRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push', models.CharField(max_length=200)),
                ('pull', models.CharField(max_length=200)),
                ('leg', models.CharField(max_length=200)),
                ('brosplit', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep', models.IntegerField(default=0)),
                ('sets', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fitability.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fitability.workoutroutine'),
        ),
        migrations.CreateModel(
            name='DayEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('entry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fitability.user')),
                ('work_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fitability.workout')),
                ('work_out_routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fitability.workoutroutine')),
            ],
        ),
    ]
