# Generated by Django 4.1.1 on 2022-09-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitability', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.BigIntegerField(default=0),
        ),
    ]
