# Generated by Django 4.1.1 on 2022-09-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fitability', '0002_alter_user_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutroutine',
            old_name='brosplit',
            new_name='workout_name',
        ),
        migrations.RemoveField(
            model_name='workoutroutine',
            name='leg',
        ),
        migrations.RemoveField(
            model_name='workoutroutine',
            name='pull',
        ),
        migrations.RemoveField(
            model_name='workoutroutine',
            name='push',
        ),
    ]
